Include link to mosquitto documentation
home-assistant/addons pull request #1695
Opened 2020-11-26 21:01 UTC by seanvictory

Fixes formatting and includes link to mosquitto documentation

2020-11-27 16:10 UTC, frenck requested changes
Small tweak

2020-11-27 16:10 UTC, frenck commented on mosquitto/README.md
>  [amd64-shield]: https://img.shields.io/badge/amd64-yes-green.svg
```suggestion
You can use this add-on to install Eclipse Mosquitto, which is an open-source (EPL/EDL licensed) message broker that implements the MQTT protocol. Mosquitto is lightweight and is suitable for use on all devices from low power single board computers to full servers. For more information, please see [mosquitto].

[mosquito]: https://mosquitto.org
[aarch64-shield]: https://img.shields.io/badge/aarch64-yes-green.svg
[amd64-shield]: https://img.shields.io/badge/amd64-yes-green.svg
```

2020-11-27 20:07 UTC, frenck approved these changes
Thanks! 👍

2020-11-27 20:07 UTC, merged

2020-11-28 12:37 UTC, MartinHjelmare commented on mosquitto/README.md
> +[mosquito]: https://mosquitto.org
Typo: -> `mosquitto`