Add propagation delay for letsencrypt with RFC2136
home-assistant/addons pull request #1729
Opened 2020-12-22 13:09 UTC by jorisdobbelsteen

When using RFC2136, the delay for propagating the DNS records is not configurable. Even though this is suggested in the documentation. This enables the configuration.

2020-12-22 13:09 UTC, homeassistant commented
Hi @jorisdobbelsteen, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#1729).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-03-21 12:32 UTC, chriscpritchard commented
Still an issue...

2021-05-23 21:44 UTC, jorisdobbelsteen commented
Ok, 2 renew cycles later (so 6 months) and this is still an issue.

2021-09-24 09:15 UTC, ludeeus requested changes
Please adjust the version in config.json to `4.11.1`
And add a changelog entry for it in CHANGELOG.md

2021-11-30 11:09 UTC, closed without merging

2022-03-04 13:12 UTC, mateuszdrab commented
Why is this not merged?

2022-06-02 21:35 UTC, mateuszdrab commented
@ludeeus 
Can we reopen and merge this finally please?