duckdns: fix ipv6 by adding "host_network: true"
home-assistant/addons pull request #1768
Opened 2021-01-21 11:09 UTC by ymarkus

fixes #1715 

Sadly, I couldn't find another way to make this work, as this addon has to curl from an ipv6 server to get the IP and default docker containers don't have an ipv6 address.

2021-01-21 11:10 UTC, homeassistant commented
Hi @ymarkus, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#1768).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-01-21 11:25 UTC, frenck requested changes
We should not just drop to the host network because of this reason.

Instead, we can ask the Supervisor for network information:

<https://developers.home-assistant.io/docs/api/supervisor/endpoints#network>

2021-01-21 13:06 UTC, ymarkus commented
I have next to no experience with docker containers, so I don't really know how I'd go about calling a GET to the host machine. If anyone else could chime in here maybe?

2021-01-25 16:07 UTC, pvizeli commented
You can use the new bashio network commands

2021-01-27 06:56 UTC, ymarkus commented
Great, thanks! How long will it take for those commands to land in hassio stable?

2021-02-03 10:34 UTC, pvizeli commented
They are in stable

2021-02-03 17:29 UTC, ymarkus commented
I'm closing this one and will open a new one as I chose a different approach.

2021-02-03 17:29 UTC, closed without merging