Add option for SSL cert algorithm in DuckDNS addon
home-assistant/addons pull request #2189
Opened 2021-09-21 17:11 UTC by tux2000

* Add optional parameter `lets_encrypt.algo` in `config.json`
* Use parameter in `run.sh` as commandline option to dehydrated
* Update documentation
* Bump version

Closes #2183

2021-09-22 21:40 UTC, sstefanowski commented
I vote for this pull request :)
It will also fix problems with Alexa playback of MP3s stored in HA (exposes via HTTPS and played using SSML Audio tag).
Currently, Alexa cannot access MP3 as it cannot make a handshake with HA secured with default algorithm of  certificate generation.

2021-09-23 09:31 UTC, sstefanowski commented
I vote for this pull request :)
It will also fix problems with Alexa playback of MP3s stored in HA (exposed via HTTPS and played using SSML Audio tag).
Currently, Alexa cannot access MP3 as it cannot make a handshake with HA secured by a certificate generated with the default algorithm.

@ludeeus 
Hi, Could you please consider the approval of this pull request? 
I checked the commit history... and it looks like in July you have committed the change including an upgrade of the dehydrated version from 0.6.5 to 0.7.0. 
Dehydrated 0.6.5 used `rsa` as the default "certificate algorithm". Dehydrated 0.7.0 uses `secp384r1`. 
Since that time some clients (also important like Amazon Alexa SSML engine) cannot do the HTTPS handshake. It can be successful if a certificate could be generated using another algorithm (e.g. `rsa`)

2021-09-23 12:44 UTC, ludeeus requested changes

2021-09-23 12:44 UTC, ludeeus commented on duckdns/data/run.sh
> +if bashio::config.has_value "algo"; then ALGO=$(bashio::config 'algo'); else ALGO="secp384r1"; fi
```suggestion
if bashio::config.has_value "lets_encrypt.algo"; then ALGO=$(bashio::config 'lets_encrypt.algo'); else ALGO="secp384r1"; fi
```

2021-09-23 12:44 UTC, ludeeus commented on duckdns/config.json
> +  "version": "1.14.0",
Changelog is missing an update

2021-09-23 12:44 UTC, ludeeus commented on duckdns/DOCS.md
> +Which public key algorithm should be used? Supported: `rsa`, `prime256v1` and `secp384r1`. Default is `secp384r1`, other algorithms might improve compatibility with older devices.
```suggestion
Public key algorithm that will be used.

Supported values: `rsa`, `prime256v1` and `secp384r1`. 

The default is `secp384r1`
```

2021-09-23 12:44 UTC, ludeeus commented on duckdns/config.json
> +      "algo": "str?"
```suggestion
      "algo": "list(rsa|prime256v1|secp384r1)?"
```

2021-09-23 16:52 UTC, tux2000 commented on duckdns/config.json
> +  "version": "1.14.0",
I will add it

2021-09-27 10:13 UTC, pvizeli commented on duckdns/config.json
> +      "algo": "list(rsa|prime256v1|secp384r1)?"
```suggestion
      "algo": "list(rsa|prime256v1|secp384r1)"
```

2021-09-27 10:13 UTC, pvizeli commented on duckdns/data/run.sh
> +if bashio::config.has_value "lets_encrypt.algo"; then ALGO=$(bashio::config 'lets_encrypt.algo'); else ALGO="secp384r1"; fi
```suggestion
ALGO=$(bashio::config 'lets_encrypt.algo')
```

2021-09-27 10:13 UTC, pvizeli approved these changes

2021-09-27 10:14 UTC, pvizeli approved these changes

2021-09-27 10:19 UTC, merged

2021-09-27 12:38 UTC, teknomar7 commented
The "algo" parameter does not appear to be optional as indicated in the documentation.  When I updated this morning, duckdns would not start back up without defining an algo k/v.  

This was seen in the logs prior to defining the k/v in the configuration (token and dns names have been redacted):
```
21-09-27 08:30:30 ERROR (MainThread) [supervisor.addons.addon] Add-on core_duckdns has invalid options: Missing option 'algo' in lets_encrypt in Duck DNS (core_duckdns). Got {'lets_encrypt': {'accept_terms': True, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}, 'token': '<redacted>', 'domains': ['<redacted>'], 'aliases': [], 'seconds': 300}
```

2021-09-27 15:15 UTC, btehan commented
Same as @teknomar7.

2021-09-27 16:19 UTC, tux2000 commented
The changes in https://github.com/home-assistant/addons/pull/2189/commits/dac5764aebe38f891456be7300f28678877eb7bd made the option non-optional. 
Not sure what works best, updating the documentation or making the option optional again. I guess forcing all users out there to manually update the configuration will not be optimal...

2021-09-27 16:36 UTC, teknomar7 commented
I would think you'd want to have the default value set if not specified.  It lists the default value in the documentation as secp384r1, so it seems like not having a default value was the mistake here (not the incorrect documentation).  Furthermore, this wasn't a major version bump, which would imply it's not a breaking change per semantic versioning when this does break functionality without some type of human interaction.

2021-09-27 16:43 UTC, tux2000 commented
Yes, this was exactly my reasoning when implementing this parameter as optional. Not sure if something with the implementation as it was in https://github.com/home-assistant/addons/pull/2189/commits/b2f282c33bab8288ee91e843e3cb7f42860c7d2c did not work or what the reason was that @pvizeli changed the behavior but not the version bump or the documentation prior to merging this to main.

2021-09-27 20:15 UTC, esenterre commented
Well. I had the problem with the upgrade that "algo" is not optional. I don't care adding line to teh config. But I don't know what (sorry for being dummy :) )

For now, I added :
`algo: secp384r1`
But should it be 
`algo: rsa`
 ?

2021-09-27 20:20 UTC, teknomar7 commented
> For now, I added :
> `algo: secp384r1`
> But should it be
> `algo: rsa`
> ?

There isn't a right or wrong answer here.  I'd go with the default secp384r1, but if you have some client devices that call your https URL that stop working, see if there are any SSL handshake issues in the logs... which might mean you'd need to switch to RSA.  The default secp384r1 is ECC and is supposed to improve performance over RSA from my understanding, but might not work on older devices that never got upgraded to work with that encryption type.  Most people probably won't notice the difference between any of the options to be honest.