Add ha_port option for nginx-proxy
home-assistant/addons pull request #2307
Opened 2021-12-15 04:00 UTC by felipecrs

I'm setting up the nginx-proxy in my HA installation just to leverage HTTP/2 because of [LL-HLS](https://www.home-assistant.io/integrations/stream/#ll-hls).

I, however, use port 8123 for external HTTPS access because my ISP blocks me from using port 443.

While I could map the nginx-proxy 443 port to something like 8124, I would prefer to maintain the 8123 port for HTTPS access, so that I don't need to re-configure all my devices.

In order to achieve that, we allow a custom HA port to be used from nginx-proxy. So that, I would set:

HA's `http.server_port` to `8124`, and map nginx-proxy 443 port to 8123.

2021-12-15 04:00 UTC, homeassistant commented
Hi @felipecrs, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2307).

Once you do that we will be able to review and accept this pull request.

Thanks!

2021-12-22 10:37 UTC, ludeeus reviewed
The supervisor already knows which port to use <https://developers.home-assistant.io/docs/api/supervisor/endpoints#core> That can be fetched with bashio instead of adding a new config option.

2021-12-22 12:16 UTC, felipecrs commented
Awesome. I'll rework it.

2021-12-22 13:44 UTC, felipecrs commented
@ludeeus done.

2021-12-22 13:46 UTC, ludeeus commented
That was fast 👍 
You would need to rebase from master to resolve the CI failure.

2021-12-22 13:48 UTC, felipecrs commented
@ludeeus done.

2021-12-22 13:49 UTC, felipecrs commented
Ops sorry, I messed up. One sec.

2021-12-22 13:52 UTC, felipecrs commented
@ludeeus done for real now.

2021-12-22 13:52 UTC, ludeeus commented
Please don't squash and force push after a review has started.

2021-12-22 13:54 UTC, ludeeus requested changes
The change looks OK to me.
Before we can merge it, you need to update the CHANGELOG.md file and bump the version in config.yaml

2021-12-22 14:05 UTC, felipecrs commented
@ludeeus done.

2021-12-22 14:09 UTC, frenck approved these changes
Agreed, looks good 👍

2021-12-22 14:11 UTC, ludeeus approved these changes
Thanks @felipecrs 👍

2021-12-22 14:13 UTC, felipecrs commented
> Please don't squash and force push after a review has started.

Oh, my bad. Some projects prefer this way so that they can use the rebase strategy for merging, but now I know what's the preferred option here.

2021-12-22 16:44 UTC, ludeeus commented on nginx_proxy/config.yaml
> +version: 3.1.0
```suggestion
version: 3.1.0
hassio_api: true
```
Needed to use the supervisor API

2021-12-22 16:51 UTC, merged