letsencrypt: add IONOS DNS provider support
home-assistant/addons pull request #2331
Opened 2022-01-01 05:42 UTC by morphis

IONOS provides API support to change DNS configuration which is
supported by certbot. See https://developer.hosting.ionos.de/docs/dns
and https://github.com/helgeerbe/certbot-dns-ionos

2022-02-10 21:26 UTC, jandelgado commented
Since IONOS is a major provider in germany, it would be great to see this PR accepted

2022-02-23 17:07 UTC, pokemon81 commented
When comes Release 4.13.0 ?

2022-03-27 19:30 UTC, LukasMayr commented
push!

2022-04-27 23:12 UTC, mdegat01 requested changes
Looks good! Small change and please let me know about my question on `ionos_endpoint`

2022-04-27 23:12 UTC, mdegat01 commented on letsencrypt/rootfs/etc/services.d/lets-encrypt/run
> +
```suggestion
```
Don't do schema validation here. If you want to do validation like this you have to do it in the `cont-init.d` file. The problem with doing validation in the run script is that if this script fails then s6 will try to restart it causing the same validation errors over and over again.

2022-07-04 00:25 UTC, closed without merging

2023-12-05 23:38 UTC, opacey commented
Hi, Did IONOS ever get merged? I don't see them in the list on the addon, despite this issue being closed and there being a recent series of minor updates released. Thanks.

2023-12-05 23:53 UTC, agners commented
This is not an issue, this is a pull request. The author would need to address the review comments. With the latest updates to newer Alpine version it would also need a rebase.

2023-12-06 00:20 UTC, opacey commented
Oops, so it is! @morphis would you consider refreshing your work on the IONOS module (and the review comments)?

2023-12-09 06:48 UTC, exp1338 commented
Is there no support any more? Ionos is not listed inside the supported DNS provides. :(