J0hnby dhcp server ntp
home-assistant/addons pull request #2376
Opened 2022-02-05 13:35 UTC by j0hnby

Modified config to bump to ver 1.3 and have ntp options and schema
Modified run.sh to include ntp servers from config if they exist
Modified docs and changelog to include additional detail.

Testing performed with local repo, started with current version, made changes, incremented version made changes as here, tested to ensure defaults arrive with upgrade, then tested with ntp servers specified and not-specified.

2022-02-05 13:35 UTC, homeassistant commented
Hi @j0hnby, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2376).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-02-12 10:11 UTC, pvizeli requested changes

2022-02-12 10:11 UTC, pvizeli commented on dhcp_server/CHANGELOG.md
> +## 1.3
```suggestion
## 1.3.0
```

2022-02-12 10:11 UTC, pvizeli commented on dhcp_server/config.yaml
> +version: "1.3"
```suggestion
version: 1.3.0
```

2022-04-27 21:42 UTC, mdegat01 approved these changes
@j0hnby Please rebase your branch and resolve the conflict with `config.yaml` (looks like you just need to add `---` to the top as a formatter added that). Then I will merge this.

2022-05-03 13:23 UTC, pvizeli commented
@j0hnby please address the lint issue

2022-05-03 16:11 UTC, merged