Bump zwave-js to 9.0.1 and zwave-js-server to 1.16.0
home-assistant/addons pull request #2424
Opened 2022-04-04 05:39 UTC by raman325

This PR isn't working correctly yet which is why it's still in draft. Details after changelog.

Changelog:
- https://github.com/zwave-js/node-zwave-js/releases/tag/v9.0.1
- https://github.com/zwave-js/node-zwave-js/releases/tag/v9.0.0

When running these changes locally, the driver loops through initialization over and over and never gets past that.

I see these logs over and over:
```
2022-04-04T05:29:45.333Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2022-04-04T05:29:45.336Z DRIVER   version 8.11.9
2022-04-04T05:29:45.337Z DRIVER
```

No errors... What I expect to see after this is:
```
2022-04-04T05:29:45.440Z CONFIG   version 8.11.7
2022-04-04T05:29:46.162Z CONFIG   Priority device configuration directory /data/store/config not found
2022-04-04T05:29:46.225Z CNTRLR   querying controller IDs...
```

2022-04-06 10:11 UTC, MartinHjelmare approved these changes
I wonder if we should delay releasing this a couple of days after the core release to not potentially confuse users about what could be the reason for any issues that come up with their devices?

2022-04-07 09:52 UTC, frenck commented
🤷 I'm happy to adopt any schedule

2022-04-09 15:31 UTC, raman325 commented
It's been a couple of days and no issues. I think we can merge?

2022-04-15 01:39 UTC, raman325 commented
this is ready to be merged.

2022-04-15 04:38 UTC, MartinHjelmare requested changes

2022-04-15 04:38 UTC, MartinHjelmare commented on zwave_js/config.yaml
> ----
This should stay I think.

2022-04-15 15:18 UTC, raman325 commented
can someone restart CI?

2022-04-15 17:42 UTC, MartinHjelmare commented
Another job failed this time.

2022-04-15 18:51 UTC, raman325 commented
`  Error: fatal: Could not read from remote repository.` Seems like maybe a problem with CI and not with the PR?

2022-04-15 22:32 UTC, raman325 commented
all good now!

2022-04-17 05:00 UTC, MartinHjelmare approved these changes

2022-04-19 06:45 UTC, merged