Add information on using an automation to renew a certificate
home-assistant/addons pull request #2489
Opened 2022-05-16 15:37 UTC by Twincarb

To save having to trawl through forums to find out how to automate the renewal of a certificate it makes sense to me to add the information to the documentation.

Fixes #2423

2022-05-16 15:38 UTC, homeassistant commented
Hi @Twincarb, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;addons#2489).

Once you do that we will be able to review and accept this pull request.

Thanks!

2022-05-31 15:54 UTC, mdegat01 requested changes
I don't mind this but I think it would be better to make a blueprint with an input for `time`. That way we can just include an "add blueprint" button in the doc and people can add it.

Do you want to make that blueprint? Or i can if you prefer. I doubt there will be much maintenance (if any) maintenance required for it.

2022-05-31 17:22 UTC, frenck commented on letsencrypt/DOCS.md
> +## Auto update with an automation
We should make this a Blueprint instead...
That makes is importable with a single button.

2022-05-31 17:37 UTC, Twincarb commented
It makes sense to me to use a Blueprint, I have just created my first Blueprint on my system to test it works. Where should it be published too?  https://community.home-assistant.io/c/blueprints-exchange 
To address @ludeeus point that HA requires restarting, is this something that can be added as an action to the Blueprint with a rule so it only restarts on the certificate being successfully being renewed?

2022-06-24 14:54 UTC, mdegat01 commented
@Twincarb Yes it should be published to that section of the forum you linked. See [sharing blueprints](https://community.home-assistant.io/t/about-blueprints/253788#sharing-blueprints-2) in the about blueprints post in that section. Basically make a post, put your blueprint in, generate a badge and then add that badge to the doc here instead of the YAML. That way its just click button to import and fill in the time to run at.

2022-07-18 16:13 UTC, elahd commented
@mdegat01 IMO most people using this addon want to set-and-forget. That is, they install the add-in, configure it once, and then just trust it to renew for them. Using a blueprint increases complexity.

As a compromise here, why not make this a configuration option for the addon? Changes would be, roughly:

1. Add a "Renew Automatically" configuration option to the addon that is on by default for new installs.
2. Change addon's `startup` attribute from `manual` to `application` so that it auto runs when HA starts up.
3. In `addons/letsencrypt/rootfs/etc/services.d/lets-encrypt`, rename `run` to `renew`.
4. Create new run script that runs the following workflow:
a. Execute `renew` script to renew certificate when addon starts.
b. If "Renew Automatically" is **on**, create a cron job that runs `renew` every Sunday at midnight. The addon should stay running.
c. If "Renew Automatically" is **off**, the addon exits as it does today.

This way, we can accommodate both what I think is the most common workflow by default while still letting edge case users do whatever they do today.

Also, since this addon is often paired with the NGINX Home Assistant SSL Proxy, we should do **_one_** of the following:
1. Add an off-by-default configuration option to the Let's Encrypt addon to automatically restart NGINX Home Assistant SSL Proxy after certificate renewal.
2. Modify NGINX Home Assistant SSL Proxy to restart after it detects that the SSL certs have been renewed. (Easiest way is to look for updates to the cert file itself; not by monitoring other services.)

Thoughts on this? I'm happy to do the work, but only want to do it if the PR will be approved 😀.

2022-08-13 15:27 UTC, elahd commented
What's the larger philosophy around what should be a blueprint vs what should be core functionality? IMO if _everyone_  who uses the add-on needs to install this blueprint in order for the addon to work as expected, the behavior should just be rolled into the addon.

It would be easier for everyone if the integration just checked the SSL cert's expiration date nightly and renewed as needed.

I proposed a more detailed proposal at https://github.com/home-assistant/addons/issues/2423#issuecomment-1187695582 but haven't gotten feedback from maintainers.

2022-10-19 17:19 UTC, closed without merging