Add propagation delay for letsencrypt with RFC2136
home-assistant/addons pull request #2513
Opened 2022-06-03 14:09 UTC by mateuszdrab

Reopening a new PR to replace https://github.com/home-assistant/addons/pull/1729

2022-06-23 21:54 UTC, mdegat01 requested changes
@mateuszdrab Please update the changelog to include your addition

2022-06-23 21:54 UTC, mdegat01 commented on letsencrypt/rootfs/etc/services.d/lets-encrypt/run
> +elif [ "${CHALLENGE}" == "dns" ] && [ "${DNS_PROVIDER}" == "rfc2136" ]; then
```suggestion
elif [ "${CHALLENGE}" == "dns" ] && [ "${DNS_PROVIDER}" == "dns-rfc2136" ]; then
```
`rfc2136` isn't an option in here:
https://github.com/home-assistant/addons/blob/d37b21354316c7266a5d7616a553bfe15da5af71/letsencrypt/config.yaml#L72-L76

Should be `dns-rfc2136`

2022-06-24 09:14 UTC, mateuszdrab commented
> @mateuszdrab Please update the changelog to include your addition

All done

2022-06-24 15:04 UTC, mdegat01 approved these changes

2022-06-24 15:05 UTC, merged

2022-06-24 15:05 UTC, mdegat01 commented
Thanks @mateuszdrab !

2022-06-24 18:15 UTC, mateuszdrab commented
Oops, saw the syntax error, thanks for correcting @mdegat01

2022-06-24 18:19 UTC, mateuszdrab commented
Oops 2, still messed up:
```
certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --certbot-dns-rfc2136:dns-rfc2136-propagation-seconds 120
```

Will need to fix the arg to `--dns-rfc2136-propagation-seconds` as documented [here](https://certbot-dns-rfc2136.readthedocs.io/en/stable/#named-arguments)

2022-06-24 18:26 UTC, mateuszdrab commented
https://github.com/home-assistant/addons/pull/2557