letsencrypt: add IONOS DNS provider support
home-assistant/addons pull request #2812
Opened 2022-12-26 05:39 UTC by morphis

IONOS provides API support to change DNS configuration which is supported by certbot. See https://developer.hosting.ionos.de/docs/dns and https://github.com/helgeerbe/certbot-dns-ionos

2023-01-25 17:45 UTC, mdegat01 requested changes
In addition to the listed changes you need to rebase.

You also need to bump the version in `config.yaml`. You added a new entry to the changelog but didn't change the version of the addon to match it.

2023-01-25 17:45 UTC, mdegat01 commented on letsencrypt/build.yaml
> +  CERTBOT_DNS_IONOS_VERSION: 2022.5.15
```suggestion
  CERTBOT_DNS_IONOS_VERSION: 2022.11.24
```
Is there a particular reason we aren't picking the current latest version here?

2023-01-25 17:45 UTC, mdegat01 commented on letsencrypt/DOCS.md
> +ionos_endpoint: ''
```suggestion
```
We should not make this an option. I know that the library makes it an option but I would expect users rarely ever change it. We should hard-code the endpoint in the addon to `https://api.hosting.ionos.com` and not make users look that information up. Unless you have reason to believe users will need to change this a lot, in which case please let me know why that is.

2023-01-25 17:45 UTC, mdegat01 commented on letsencrypt/rootfs/etc/services.d/lets-encrypt/run
> +    PROVIDER_ARGUMENTS+=("--authenticator" "${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" /data/dnsapikey)
```suggestion
    bashio::config.require 'dns.ionos_prefix'
    bashio::config.require 'dns.ionos_secret'
    PROVIDER_ARGUMENTS+=("--authenticator" "${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" /data/dnsapikey "--${DNS_PROVIDER}-propagation-seconds" "${PROPAGATION_SECONDS}")
```
Need to support the propagation seconds option. Also removed the endpoint config option as mentioned above.

2023-03-19 11:27 UTC, jandelgado commented
@morphis , any chance we get this MR successfully merged? It seems to be already the 5th attempt, after #2331, #2626 (my shot), #2718 and #2721 - so finally getting this feature out of the door would be highly appreciated. Thanks for your efforts, hang on!

2023-05-07 21:06 UTC, gomble commented
Hello when will this PR merged ?

2023-05-07 21:35 UTC, gomble commented
@morphis can you have a look into your PR and correct the suggestions?

2023-05-09 06:10 UTC, gomble approved these changes

2023-07-15 08:06 UTC, closed without merging

2023-07-22 01:58 UTC, sblu commented
@morphis It would be great if you can get this PR in.

2023-09-11 21:05 UTC, mido1978 commented
Hi guys, 
is this topic closed and away now? You would me (and others) very happy, if you could bring IONOS into this.

Many thanks!

2023-11-15 23:58 UTC, opacey commented
I'm very keen to have dns-ions added to the package, is it just a matter of finding someone with time to review and merge it?

2024-01-03 15:01 UTC, port3306 commented
Why is the status closed? Would be nice if someone could review and merge it.

2024-01-03 15:22 UTC, agners commented
@port3306 the PR got closed because it got stale. The author did not address the review comments.

Unless the original author revives this PR, the common process for another author would be to pick the changes from here, address review feedback and open a new PR.