Change credentials-schema
home-assistant/addons pull request #2837
Opened 2023-01-15 20:19 UTC by RyanFlm

Changed the credentials-schema to allow percent(%)-symbols in passwords.

2023-01-25 18:49 UTC, mdegat01 commented
Did you test this? The reason for the restrictions on `%` is because here's how this information is actually used in this addon:
https://github.com/home-assistant/addons/blob/b734b3ca9fb25b9e051891bfbb750865f1e59ba1/rpc_shutdown/data/run.sh#L29

Here's the man page for the [net command](https://linux.die.net/man/8/net). Notice that in this doc the `-U` option is documented like this `[-U username[%password]]`. It requires a `%` symbol separating the username and password.

Because of that `%` is definitely not allowed in the username. I don't know if it has a problem with `%` in the password or not, depends on how its implemented. I can't seem to find any info on this googling and don't have an easy way to test this.

Can you show me this working fine somewhere else? Just run the following command after plugging in your info to confirm it work.
```
ADDRESS="<host address>"
USERNAME="<username>"
PASSWORD="<password with %>"
net rpc shutdown -I "$ADDRESS" -U "${USERNAME}%${PASSWORD}" -t 0
```
Please blank out any sensitive info in things you share (credentials mostly).

If doing a shutdown is too disruptive I think you can also just request info with `net rpc info`.

2023-01-25 18:50 UTC, mdegat01 requested changes
Please run the requested test in the comments. Assuming that test and this change is safe to make you also need to bump the version of the addon in `config.yaml` and add an entry to the changelog.

2023-01-26 00:20 UTC, RyanFlm commented
I've run the required command in my local network and it worked fine. After the "-U" you can see the Username in front of the first '%'. After that, the password with a second '%'. The command succeeded.

![prove](https://user-images.githubusercontent.com/50547464/214722737-bcf66601-6bbf-46c2-bdf9-0bb0ca8f694e.png)

I found a comment on the internet where someone stated that this should be possible, but I can't find the source anymore. But I've tried it myself and it worked.

I'll make the version bump and changelog tomorrow.

2023-02-19 09:24 UTC, Joshndroid commented
can we get this looked at further and merged... I have a % in a password sadly and i can't use this pc in RPC

2023-02-22 21:44 UTC, RyanFlm commented
I've messed up the branch where I made the version changes in my fork so the commits look a bit wonky but the changes are what is requested.
- Actual change
- Version bump
- Changelog entry

2023-04-20 06:51 UTC, agners commented on rpc_shutdown/CHANGELOG.md
> +- Modified the regex for password verification to allow '%' in the password
```suggestion
- Allow '%' sign in the password
```

2023-04-20 07:10 UTC, agners approved these changes

2023-04-20 07:11 UTC, merged