samba: Migrate add-on layout to S6 Overlay
home-assistant/addons pull request #3001
Opened 2023-04-22 08:59 UTC by lmagyar

No functional change.

Just migrates files to new S6 layout.

I saw a planned update to Alpine 3.17 and thought it's a good time to change this also.

2023-04-22 10:01 UTC, frenck commented
I have this + a bunch of more changes ready to go... while I was awaiting #2997.

This PR is running through my planned maintenance.

../Frenck

2023-04-22 11:25 UTC, lmagyar commented
OK, closing, no problem. :)
Made another small PR, no more PR planned from me.

2023-04-22 11:28 UTC, frenck commented
I actually have this and more changes already pending, you are now running through my samba add-on maintenance which I started in #

2023-04-22 11:29 UTC, frenck commented
I don't think you need to close this PR? Like... I will be re-opening the same one 🤷 

(efforts have already been duplicated, that is all).

2023-04-22 12:16 UTC, lmagyar commented
OK, I simply didn't want to disturb you. I reopened it and made it draft like the other #3002.

I will wait for the next samba release before I click anything. :)

2023-10-01 21:36 UTC, lmagyar commented
Can be reopened, github actions bot didn't send notification about the stale label on this draft PR, only when closed it.

2023-11-11 11:16 UTC, frenck requested changes

2023-11-11 11:16 UTC, frenck commented on samba/rootfs/etc/s6-overlay/s6-rc.d/smbd/finish
> +declare exit_code
Unused variable

```suggestion
```

2023-11-11 11:16 UTC, frenck commented on samba/rootfs/etc/s6-overlay/s6-rc.d/nmbd/finish
> +declare exit_code
```suggestion
```

2023-11-12 09:50 UTC, frenck commented on samba/config.yaml
> +version: 11.1.0
```suggestion
version: 11.0.0
```

2023-11-12 09:50 UTC, frenck commented on samba/config.yaml
> +version: 11.1.0
Adding this one, to avoid the upgrade/release. Got another PR inbound for the 11.1.0

2023-11-12 10:15 UTC, frenck approved these changes
Thanks, @lmagyar 👍 

../Frenck

2023-11-12 10:15 UTC, merged