Bump zwave-js to 10.23.2
home-assistant/addons pull request #3094
Opened 2023-06-12 04:34 UTC by raman325

Mostly bug fixes

Changelog
- [Bump Z-Wave JS to 10.23.0](https://github.com/zwave-js/node-zwave-js/releases/tag/v10.23.0)
- [Bump Z-Wave JS to 10.23.1](https://github.com/zwave-js/node-zwave-js/releases/tag/v10.23.1)
- [Bump Z-Wave JS to 10.23.2](https://github.com/zwave-js/node-zwave-js/releases/tag/v10.23.2)

CC @AlCalzone feel free to suggest release note changes but I highlighted the ones I thought would be relevant to users

2023-06-12 10:24 UTC, MartinHjelmare approved these changes

2023-06-12 13:49 UTC, AlCalzone requested changes
Mostly bugfixes seems correct. The one feature is probably not relevant for core addon users.

Maybe highlight this:
- Fixed an issue which could cause temperature to switch to Celsius instead of Fahrenheit

2023-06-12 13:55 UTC, AlCalzone requested changes

2023-06-12 13:55 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- The Celsius temperature scale is no longer set as a preferred scale by default
```suggestion
- Fixed an issue which could cause temperature to be shown in Celsius instead of Fahrenheit
```

2023-06-12 13:55 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- Nodes are no longer assumed to be awake when they send a NonceGet
```suggestion
- Fixed an issue which could cause devices to be incorrectly considered to be awake
```

2023-06-12 13:55 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- Disable optimistic value update for unsupervised Barrier Operator CC commands
```suggestion
- Verify state change for barrier devices without support for Supervision CC instead of assuming commands to succeed
```

2023-06-12 13:55 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- Improve handling of unexpected/incorrect commands during S2 bootstrapping
```suggestion
```
not relevant enough IMO

2023-06-12 15:23 UTC, merged

2023-07-07 15:38 UTC, niemyjski commented
@raman325 Is there any plan to follow up with a new pr for the latest 11.x version?

2023-07-07 17:06 UTC, raman325 commented
> @raman325 Is there any plan to follow up with a new pr for the latest 11.x version?

believe it or not, I do not have to be the one to open a PR to update the addon 😉 I don't really have a plan for updates unless I see something obviously critical or it's tied to changes in the lib/integration. It would be a good idea to get to latest, I can open a PR this weekend if no one gets to it before then (hint hint 😁 )

2023-07-07 18:36 UTC, niemyjski commented
If I get time I'll open a pr, just saw you normally did I it so wasn't sure if you had a specific process.