matter_server: Bump Python Matter server to 3.5.2
home-assistant/addons pull request #3112
Opened 2023-06-23 15:12 UTC by agners

With this upgrade also use the Python Matter container image as base for this add-on.

2023-06-23 15:32 UTC, marcelveldt approved these changes

2023-06-23 15:53 UTC, frenck requested changes
The version didn't bump in the add-on config, was that intentional?

2023-06-27 20:04 UTC, agners commented
> The version didn't bump in the add-on config, was that intentional?

No, that wasn't intentional. It is fixed now!

2023-06-27 20:29 UTC, frenck approved these changes

2023-06-27 21:26 UTC, merged