Fix for log level being NULL in Matter add-on
home-assistant/addons pull request #3117
Opened 2023-06-27 18:49 UTC by marcelveldt

Bandaid solution for some issue reports we received where the loglevel retrieved from bashio was "NULL", resulting in a crashing add-on. This will set a default of info when the call returns empty.

2023-06-27 18:50 UTC, frenck requested changes
Don't forget to bump the version and update the changelog :)

2023-06-27 18:52 UTC, marcelveldt commented
> Don't forget to bump the version and update the changelog :)

Well, I'm in doubt now as I also want to release a beta add-on ....

2023-06-28 08:02 UTC, MartinHjelmare commented
Bumping the version of the add-on isn't interesting in the PR title. Almost all PRs targeting add-ons will bump the version of the add-on. We should talk about what the change in the add-on is.

2023-06-28 08:03 UTC, MartinHjelmare commented
I suggest doing separate PRs for the server bump and the logging option change.

2023-06-28 08:12 UTC, marcelveldt commented
> I suggest doing separate PRs for the server bump and the logging option change.

haha, that's what I did and then was asked to do it all at once :-)

2023-06-28 09:29 UTC, agners commented on matter_server/build.yaml
> +  MATTER_SERVER_VERSION: 3.6.1
This is no longer used/needed since we base on the Matter Server container image now. You need to bump the base image used in `build.yaml` now.

2023-06-28 09:34 UTC, closed without merging