Feat: add timestamp to git_pull logs
home-assistant/addons pull request #3224
Opened 2023-09-25 19:33 UTC by danielgomezrico

The logs are like:

```
and the repository exists.
[Error] Git fetch failed
Check SSH connection
[Warn] No valid SSH connection for git@github.com
[Info] Start adding SSH key
[Info] Setup deployment_key on id_rsa
[Info] Local git repository exists
```

# Expected

They contain the timestamp:
```
and the repository exists.
[Error][32132] Git fetch failed
Check SSH connection
[Warn][32132] No valid SSH connection for git@github.com
[Info][32132] Start adding SSH key
[Info][32132] Setup deployment_key on id_rsa
[Info][32132] Local git repository exists
```

2023-09-25 21:58 UTC, danielgomezrico commented
Im not really sure how to test this... I tried forking, editing and installing the custom repo on my side (https://github.com/danielgomezrico/addons/commits/master) but I get:

```console
Failed to install add-on
Can't install homeassistant/aarch64-addon-git_pull:7.13.2: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=7.13.2&fromImage=homeassistant%2Faarch64-addon-git_pull&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-git_pull:7.13.2 not found: manifest unknown: manifest unknown")
```

![image](https://github.com/home-assistant/addons/assets/76348/567a9210-35d8-4def-a4ce-c3c83a3abb78)

2023-10-20 22:13 UTC, danielgomezrico commented
Hi @pvizeli, can you take a look? If you can put `hacktoberfest-accepted` label on it, it would be wonderful.

2023-11-06 13:51 UTC, agners commented
@danielgomezrico you need to adjust `config.yaml` to point to the location of where you pushed the add-on to.

2023-11-27 11:29 UTC, frenck requested changes

2023-11-27 11:29 UTC, frenck commented on git_pull/data/run.sh
> +    log_i "Start adding SSH key"
```suggestion
    bashio::log.info "Start adding SSH key"
```

2023-11-27 11:29 UTC, frenck commented on git_pull/data/run.sh
> +        log_w "No valid SSH connection for $DOMAIN"
```suggestion
        bashio::log.warning "No valid SSH connection for $DOMAIN"
```

2024-02-02 12:07 UTC, closed without merging