Bump Z-Wave JS to 12.5.5 and Z-Wave JS Server to 1.35.0
home-assistant/addons pull request #3569
Opened 2024-04-17 06:18 UTC by raman325

Aside from the config file changes, this bump brings Long Range support. The integration doesn't support long range yet but we need this in place for when we add support

Changelogs:
- [Z-Wave JS Server 1.35.0](https://github.com/zwave-js/zwave-js-server/releases/tag/1.35.0)
- [Z-Wave JS 12.5.5](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.5)
- [Z-Wave JS 12.5.4](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.4)
- [Z-Wave JS 12.5.3](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.3)
- [Z-Wave JS 12.5.2](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.2)
- [Z-Wave JS 12.5.1](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.1)
- [Z-Wave JS 12.5.0](https://github.com/zwave-js/node-zwave-js/releases/tag/v12.5.0)

2024-04-17 07:10 UTC, AlCalzone requested changes

2024-04-17 07:10 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- Z-Wave JS: Add Z-Wave long range support
Z-Wave Long Range is a name, we should capitalize it everywhere consistently.

2024-04-17 07:10 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +- Z-Wave JS: Map more Basic CC values to more useful command classes
Slightly obfuscated in the changelog, but 12.5.4 also fixes an issue where spurious Basic (and other) values could show up when they shouldn't.

2024-04-17 07:10 UTC, AlCalzone commented on zwave_js/CHANGELOG.md
> +### Bug fixes
- Z-Wave JS: Fixed a crash that could happen in some cases during the Configuration CC interview

only visible in Z-Wave JS UI, but so are the NVM and association related fixes:

- Z-Wave JS: Fixed an issue where provisioning entries could disappear

2024-04-18 10:58 UTC, MartinHjelmare approved these changes

2024-04-18 10:58 UTC, merged